### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [pocket0yuka/kotonoha_drink#63]
MVPリリースおめでとうございます！
以下にレビュー内容記載しますので本リリースまでにやることの参考にして下さい
また、このissueのコメントで本リリースの予定日を教えてください

全体的に綺麗に作れていました！
オートコンプリートやOpenAI APIの使用など技術的にも頑張っていることが伺えました

## ヘッダーのドリンク検索
検索ボタンで作成がはじまることに違和感を感じました
また、検索だと思って行うとかなり時間がかかってしまうのですでにユーザーが作成したドリンクやメニュー(メニューについては後述します)にある内容を表示する方が検索っぽいかなと思いました
作成したいのであれば作成することがユーザーに伝わるようにしてあげると良いと思います
おこじょは可愛かったです

## ヘッダーのメニュー
ログアウトのリンクが真ん中にあったりするのでいろんなWebサービスを見て良くある形にしてあげると良いかなと思いました

## メニュー表
メニュー表を閲覧するときも一回一回時間がかかるのでメニューにはすでに生成済みのデータを表示するだけにするとリクエスト回数も減るし、待ち時間も減って良いかなと思いました

## bookmark
ブックマークとドリンク言葉集が結びつきにくいかなと思ったので、
お気に入りのドリンク言葉集や保存したドリンク言葉一覧のようにしてあげるとわかりやすくなるかもです

↑に合わせてbookmarkする際の文言を統一してあげると良いと思います

## ドリンクを注文する
ドリンクを注文するページのフォームにの送信ボタンが検索なので注文するとかに統一してあげると良いと思います

## 投稿
投稿や日記など文言が統一されていないのが気になりました
修正予定だと思いますがPCだと表示が崩れているように見えてしまうので整えてあげると良いと思います
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/f87dfdd3d71fefb033968dbaa0baffb9.png)](https://startup-technology.gyazo.com/f87dfdd3d71fefb033968dbaa0baffb9)
また、ドリンク言葉とのつながりがあまり感じられなかったため何を投稿すればいいか、何を目当て人投稿ページを閲覧するかがわかりにくかったので導線をドリンク言葉の生成後などのページに設けるなどして投稿が集まりやすい工夫や投稿の意図がわかりやすい工夫をしてあげても良いかもです

## socialsharings
アイコンからはなんのページなのかがわからないので伝え方を工夫されるとより良くなると思います

**Comment by pocket0yuka** [comment]
お疲れ様です！
レビューありがとうございます
上記、承知致しました
本リリースは3/3の予定で実装を進めたいと思います。
よろしくお願い致します
